name: Build and upload Zuri package for POSIX platforms
on:
  push:
    branches:
      - master

jobs:

  build-posix:
    uses: ./.github/workflows/build-package.yml

    strategy:
      matrix:
        platform: ${{ fromJSON(vars.POSIX_PLATFORMS) }}

    secrets: inherit
    with:
      build_type: ${{ matrix.platform.build_type }}
      build_runner: ${{ matrix.platform.build_runner }}
      conan_profile: ${{ matrix.platform.conan_profile }}
      install_dependencies_script: ${{ matrix.platform.install_dependencies_script }}

    name: "Build ${{ matrix.platform.conan_profile }}"

  promote-to-integ:
    uses: ./.github/workflows/promote-package.yml
    needs: build-posix

    strategy:
      matrix:
        platform: ${{ fromJSON(vars.POSIX_PLATFORMS) }}

    secrets: inherit
    with:
      build_runner: ${{ matrix.platform.build_runner }}
      conan_profile: ${{ matrix.platform.conan_profile }}

    name: "Promote ${{ matrix.platform.conan_profile }}"

  trigger-ci:
    uses: ./.github/workflows/ci.yml
    needs: promote-to-integ

    secrets: inherit

    name: "Trigger Integration"
