name: Build and upload Zuri package for POSIX platforms
on:
  push:
    branches:
      - master

jobs:

  build-posix:
    uses: ./.github/workflows/build-package.yml

    strategy:
      matrix:
        platform: [
          { # ubuntu2404-arm64-debug
            build_type: "Debug",
            build_runner: "ubuntu-24.04-arm",
            conan_profile: "Ubuntu24.04-armv8-Debug",
            install_dependencies_script: "sudo apt-get install clang"
          },
          #{ # ubuntu2404-x86_64-debug
          #  build_type: "Debug",
          #  build_runner: "ubuntu-24.04",
          #  conan_profile: "Ubuntu24.04-x86_64-Debug",
          #  install_dependencies_script: "sudo apt-get install clang"
          #},
          { # macos-arm64-debug
            build_type: "Debug",
            build_runner: "macos-15",
            conan_profile: "MacOS-armv8-Debug"
          }
        ]

    secrets: inherit
    with:
      build_type: ${{ matrix.platform.build_type }}
      build_runner: ${{ matrix.platform.build_runner }}
      conan_profile: ${{ matrix.platform.conan_profile }}
      install_dependencies_script: ${{ matrix.platform.install_dependencies_script }}

    name: "Build ${{ matrix.platform.conan_profile }}"